#version 3 of DOCKER COMPOSE
version: '3'
services:
  mongodb:
    build: ./db
    ports:
      - "27017:27017"
    #so that data stored in mongo are really persisted even if command "docker system prune is applied"
    volumes:
      - ./data/persistedMongo:/data/db
  back_end:
    build: ./back_end
    ports:
      - "4001:80"
    links:
      - mongodb
