#version 3 of DOCKER COMPOSE
version: '3'
services:
  mongodb:
    build: ./db
    ports:
      - "27017:27017"
  back_end:
    build: ./back_end
    ports:
      - "4001:80"
    links:
      - mongodb
